// Tile legend: map character -> tile name + behavior flags.
// Engine-owned. Data agents place chars; this file defines what they mean.
const LEGEND = {
  '.': { t: 'grass', solid: false },
  ',': { t: 'dirt', solid: false },
  '=': { t: 'road', solid: false },
  'L': { t: 'road_line', solid: false },
  '-': { t: 'sidewalk', solid: false },
  't': { t: 'tallgrass', solid: false, cover: true },
  'T': { t: 'tree', solid: true },
  '*': { t: 'debris', solid: true },
  '~': { t: 'water', solid: true, water: true },
  'P': { t: 'pump', solid: true, pump: true },
  '#': { t: 'brick', solid: true },
  'n': { t: 'brick_window', solid: true },
  'W': { t: 'wood', solid: true },
  'o': { t: 'wood_window', solid: true },
  'f': { t: 'fence', solid: true },
  'G': { t: 'gate', solid: true, gate: true },
  'D': { t: 'door', solid: true, door: true },
  'B': { t: 'boarded', solid: true, boarded: true },
  'g': { t: 'glassdoor', solid: true, glass: true },
  'r': { t: 'rail', solid: false },
  'R': { t: 'plank', solid: false },
  '^': { t: 'gap', solid: false, hazard: 'gap' },
  'h': { t: 'glasshaz', solid: false, hazard: 'glass' },
  'w': { t: 'wire', solid: false, hazard: 'wire' },
  'c': { t: 'car_l', solid: true, car: true },
  'd': { t: 'dumpster', solid: true },
  'v': { t: 'vending', solid: true, vending: true },
  's': { t: 'shelf', solid: true },
  'k': { t: 'desk', solid: true },
  'x': { t: 'boxcar', solid: true },
  'F': { t: 'firepit', solid: true, fire: true },
  'E': { t: 'bed', solid: true, sleep: true },
  'S': { t: 'sign', solid: true },
  'O': { t: 'cache', solid: true },
  'I': { t: 'floor', solid: false },
  'u': { t: 'floor_rug', solid: false },
  '+': { t: 'doorway', solid: false, exit: true },
  'C': { t: 'counter', solid: true },
};
